### PR TITLE
Required network id for lbr

### LINKED ISSUE #26: If you don't specify a network id and instance ids, the load balancer rule fails to create because of a concurrency issue
Since there's no dependency between a lbr and a load balancing tier, it tries to create the lbr first and fails to create because it can't find the tier.

I think the network id should be required.

### PR DESCRIPTION
**Pull request by franzpgarcia**
fixes #26

### CODE REVIEW

File: cloudca/resource_cloudca_load_balancer_rule.go [hunk 1]
```diff
@@ -118,7 +118,7 @@ func createLbr(d *schema.ResourceData, meta interface{}) error {
 
 	if instanceIdsPresent {
 		var instanceIds []string
-		for _, id := range d.Get("instance_ids").([]interface{}) {
+		for _, id := range d.Get("instance_ids").(*schema.Set).List() {
```
Comment (pdube) [inline cloudca/resource_cloudca_load_balancer_rule.go]: This was done in a previous PR, no?

Comment (franzpgarcia) [inline cloudca/resource_cloudca_load_balancer_rule.go]: The branch was out of date. It doesn't appear anymore when targeting the dev branch.

File: cloudca/resource_cloudca_load_balancer_rule.go [hunk 2]
```diff
@@ -3,11 +3,12 @@ package cloudca
 import (
 	"errors"
 	"fmt"
+	"strconv"
```
Comment (simongodard) [inline cloudca/resource_cloudca_load_balancer_rule.go]: Where to you use this import?
